spring:
  application:
    name: tast-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/taskforge_db
    username: postgres
    password: 12345
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    spring:
      liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yaml

